/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VibesRouteImport } from './routes/vibes'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const VibesRoute = VibesRouteImport.update({
  id: '/vibes',
  path: '/vibes',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/lyrics': typeof LyricsRoute
  '/upload': typeof UploadRoute
  '/vibes': typeof VibesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/lyrics': typeof LyricsRoute
  '/upload': typeof UploadRoute
  '/vibes': typeof VibesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/generate': typeof GenerateRoute
  '/lyrics': typeof LyricsRoute
  '/upload': typeof UploadRoute
  '/vibes': typeof VibesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calendar' | '/generate' | '/lyrics' | '/upload' | '/vibes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendar' | '/generate' | '/lyrics' | '/upload' | '/vibes'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/generate'
    | '/lyrics'
    | '/upload'
    | '/vibes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  GenerateRoute: typeof GenerateRoute
  LyricsRoute: typeof LyricsRoute
  UploadRoute: typeof UploadRoute
  VibesRoute: typeof VibesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vibes': {
      id: '/vibes'
      path: '/vibes'
      fullPath: '/vibes'
      preLoaderRoute: typeof VibesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  GenerateRoute: GenerateRoute,
  LyricsRoute: LyricsRoute,
  UploadRoute: UploadRoute,
  VibesRoute: VibesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
